//===- Contradiction.h - Contradiction result helper ------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_TYPING_CONTRADICTION_H
#define MLIR_TYPING_CONTRADICTION_H

#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Value.h"
#include "mlir/Typing/Context.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/raw_ostream.h"

#include <concepts>
#include <memory>
#include <optional>
#include <type_traits>
#include <vector>

namespace mlir::Typing {

class AbstractTypeChecker;

/// Stores an IR source location for some Evidence.
///
/// A source can be one of the following:
///
///   - @c nullptr
///   - Context       (Context *)
///   - Dialects      (Dialect *)
///   - Definitions   (Value)
///   - Uses          (OpOperand *)
///   - Users/Owners  (Operation *)
///   - Other         (Location)
///
/// Some sources have an associated Location in the IR, which can be queried by
/// the `getLoc` method. Additionally, a textual representation of the source
/// can be printed to a stream for debugging purposes.
class Source {
  using Impl = llvm::PointerUnion<
    Context *,
    Dialect *,
    Value,
    OpOperand *,
    Operation *,
    Location>;

public:
  /*implicit*/ Source() = default;
  /*implicit*/ Source(Context *context) : impl(context) {}
  /*implicit*/ Source(Dialect *dialect) : impl(dialect) {}
  /*implicit*/ Source(Value definition) : impl(definition) {}
  /*implicit*/ Source(OpOperand *use) : impl(use) {}
  /*implicit*/ Source(OpOperand &use) : Source(&use) {}
  /*implicit*/ Source(Operation *op) : impl(op) {}
  /*implicit*/ Source(Location loc) : impl(loc) {}

  /// Gets the underlying pointer union.
  [[nodiscard]] Impl getPointer() const { return impl; }

  /// Gets the Location of the source, if it has any.
  ///
  /// @retval nullopt     Source is @c nullptr or type checker.
  /// @retval Location    IR Location for @p source .
  [[nodiscard]] std::optional<Location> getLoc() const;

  /// Prints a textual representation of the source to @p os .
  void print(llvm::raw_ostream &os) const;

  friend llvm::raw_ostream &operator<<(llvm::raw_ostream &os, const Source &source) {
    source.print(os);
    return os;
  }

  /// Determines whether the underlying pointer is @c nullptr .
  explicit operator bool() const { return !impl.isNull(); }

private:
  Impl impl;
};

/// Concept matching a type that a DiagnosticArgument can be constructed from,
/// except something that might be a dangling StringRef.
template<class T>
concept safe_diag_arg =
  std::constructible_from<DiagnosticArgument, T>
  && (std::is_base_of_v<Attribute, std::remove_cvref_t<T>>
     || std::same_as<StringLiteral, std::remove_cvref_t<T>>
     || !std::convertible_to<T, StringRef>);

/// Stores a piece of evidence generated by the type checker.
///
/// When type checking fails (gets stuck), the type checker is expected to
/// explain (via diagnostics) why. To provide an accurate trace, evidence is
/// collected. A piece of evidence has an optional Source in the IR, and a list
/// of DiagnosticArguments that explain it.
///
/// Effectively, this type is a lazy builder for a Diagnostic, with the added
/// benefit of allowing a more precise and tractable source location.
class Evidence {
  using args_storage = SmallVector<DiagnosticArgument>;
  using string_storage = std::vector<std::unique_ptr<char[]>>;

public:
  /// Initializes some Evidence.
  ///
  /// @param          source      Optional source.
  /*implicit*/ Evidence(Source source = {})
      : source(source), args(), strings() {}

  /// Gets the Source.
  [[nodiscard]] Source getSource() const { return source; }
  /// Gets the description.
  [[nodiscard]] ArrayRef<DiagnosticArgument> getArgs() const { return args; }

  /// Gets the Location of the source, if any.
  [[nodiscard]] std::optional<Location> getLoc() const {
    return source.getLoc();
  }

  /// Creates a diagnostic built from this evidence.
  ///
  /// @param              defaultLoc  Default Location.
  /// @param              severity    DiagnosticSeverity.
  ///
  /// @pre    `severity != DiagnosticSeverity::Note`
  ///
  /// @return InFlightDiagnostic.
  InFlightDiagnostic toDiagnostic(
    Location defaultLoc,
    DiagnosticSeverity severity = DiagnosticSeverity::Error) const;

  /// Attaches a note built from this evidence to @p diag .
  ///
  /// @param  [in,out]  diag  Diagnostic.
  ///
  /// @return Newly created note Diagnostic.
  Diagnostic &toNote(Diagnostic &diag) const;

  /// Appends a string literal.
  template<std::size_t Len>
  Evidence &append(const char (&literal)[Len]) {
    return append(StringLiteral::withInnerNUL(literal));
  }
  /// Interns @p str into an owned buffer and appends it.
  Evidence &append(const SmallVectorImpl<char> &str);
  /// Appends @p str if it is a reference, otherwise interns and appends it.
  Evidence &append(const Twine &str);
  /// Prints into an interned string and appends it.
  Evidence &append(llvm::function_ref<void(llvm::raw_ostream &)> printer);
  /// Appends a DiagnosticArgument with guaranteed lifetime.
  Evidence &append(safe_diag_arg auto&& arg) {
    args.emplace_back(std::forward<decltype(arg)>(arg));
    return *this;
  }
  /// Prints an instance to an interned string and appends it.
  template<class T>
    requires (requires (const T &t, llvm::raw_ostream &os) { t.print(os); })
  Evidence &append(const T& printable) {
    return append([&](llvm::raw_ostream &os) { printable.print(os); });
  }

  /// Prints a textual representation of the evidence to @p os .
  void print(llvm::raw_ostream &os) const;
  /// Prints a textual representation to `llvm::errs()`.
  void dump() const;

  friend llvm::raw_ostream &operator<<(llvm::raw_ostream &os, const Evidence &evidence) {
    evidence.print(os);
    return os;
  }

private:
  Source source;
  args_storage args;
  string_storage strings;
};

// FIXME: If we make this a hidden friend, it is not SFINAE friendly :(
inline auto operator<<(Evidence &evidence, auto&& arg)
  -> decltype(evidence.append(std::forward<decltype(arg)>(arg)))
{
  return evidence.append(std::forward<decltype(arg)>(arg));
}

/// Result of a typing rule application.
///
/// A Contradiction records a chain of Evidence that describes why the
/// application of a typing rule has failed. This can happen in one of two
/// different ways, which are separate states of the Contradiction object:
///
///   - The rule could not be applied because some premise is indeterminate.
///
///     This is usually not a fatal (i.e., type checking getting stuck) error,
///     since MLIR type checking always proceeds on valid IR, which must already
///     have a valid typing. In other words, this indicates that no refinement
///     is possible given the current context.
///
///     This is represented by a Contradiction constructed without a source. It
///     converts to `success` and returns @c false for isFatal().
///     A default-constructed Contradiction is also indeterminate.
///
///   - The rule can never be applied because a contradiction was found.
///
///     This indicates a fatal error in type checking, meaning that the current
///     context is contradictory. Once such a contradiction is found, type
///     checking must be aborted, because no further recovery is possible.
///
///     This is represented by a Contradiction constructed with a source. It
///     converts to `failure` and returns @c true for isFatal().
///
/// A fatal contradiction is created using AbstractTypeChecker::fatal(Source),
/// which associates the instance with a parent that will eventually handle it.
///
/// The intended use is to return an `std::optional<Contradiction>` and use it
/// in an if statement as follows:
///
/// ```c++
/// if (auto maybeContra = applyRule()) {
///   // The rule was not applied, attach a useful trace.
///   maybeContra->attachNote(here) << "required from here";
///   // Convert to a LogicalResult after attempting to handle it.
///   return maybeContra->handle(op->getLoc());
/// }
/// ```
///
/// Additionally, a Contradiction may have a causing Contradiction associated
/// with it. This allows for greater reuse and more precise diagnostics in
/// type checking implementations that evaluate partial functions:
///
/// ```c++
/// if (auto maybeContra = applyRule()) {
///   // The rule was not applied, leading to a cascading failure.
///   maybeContra->becomesEffect(here) << "unable to reconcile types";
///   // Chain along the Contradiction.
///   return maybeContra;
/// }
/// ```
class [[nodiscard]] Contradiction : public Evidence {
  using note_storage = llvm::SmallVector<Evidence>;

public:
  /// Initializes an indeterminate Contradiction without a parent.
  /*implicit*/ Contradiction() = default;

  /*implicit*/ Contradiction(Contradiction &&) = default;
  Contradiction &operator=(Contradiction &&) = default;

  /// Gets the parent AbstractTypeChecker.
  [[nodiscard]] AbstractTypeChecker *getParent() const { return parent; }
  /// Gets the causing Contradiction, if any.
  [[nodiscard]] const Contradiction *getCause() const { return cause.get(); }
  /// Gets the attached notes, if any.
  [[nodiscard]] ArrayRef<Evidence> getNotes() const { return notes; }

  /// Turns this contradiction into a new effect of its former self.
  ///
  /// Moves the current state of the Contradiction into an owned reference to
  /// the cause and creates new evidence at @p at . If @p at is @c nullptr , the
  /// new state is an indeterminate Contradiction.
  ///
  /// @param              at  Optional source of the effect.
  ///
  /// @pre    `hasEvidence()`
  ///
  /// @return `*this`
  ///
  /// @post   `hasEvidence()`
  /// @post   `isFatal() == static_cast<bool>(at)`
  Contradiction &becomesEffect(Source at = {});

  /// Attaches a new piece of Evidence as a note at @p source .
  ///
  /// @param              at  Optional source of the note.
  ///
  /// @return Newly recorded note Evidence.
  Evidence &attachNote(Source at = {}) { return notes.emplace_back(at); }

  /// Indicates whether this is a fatal contradiction.
  [[nodiscard]] bool isFatal() const { return static_cast<bool>(getSource()); }

  /// Attempts to handle the contradiction at the parent.
  ///
  /// @param              loc Default Location.
  ///
  /// @retval `failure` Type checking should abort.
  /// @retval `success` Type checking should resume.
  LogicalResult handle(Location loc);

  /// Prints a textual representation of the Contradiction to @p os .
  void print(llvm::raw_ostream &os) const;
  /// Prints a textual representation of the Contradiction to `llvm::errs()`.
  void dump() const;

  friend llvm::raw_ostream &operator<<(llvm::raw_ostream &os, const Contradiction &contra) {
    contra.print(os);
    return os;
  }

  template<class Arg>
    requires (
      requires (Evidence &evidence, Arg arg) {
        evidence << std::forward<Arg>(arg);
      }
    )
  friend Contradiction &operator<<(Contradiction &contra, Arg&& arg) {
    static_cast<Evidence &>(contra) << std::forward<Arg>(arg);
    return contra;
  }

private:
  explicit Contradiction(AbstractTypeChecker *parent, Source source)
      : Evidence(source), parent(parent) {
    assert(parent);
  }

  AbstractTypeChecker *parent;
  std::unique_ptr<Contradiction> cause;
  note_storage notes;

  friend class AbstractTypeChecker;
};

/// Reports all diagnostics that can be derived from this Contradiction.
///
/// Creates and reports a diagnostic for each causing Contradiction, starting
/// with the current one. If this Contradiction is indeterminate, only
/// wanings will be generated from it.
///
/// @param              loc       Default Location.
/// @param              contra    Contradiction.
/// @param              severity  Maximum DiagnosticSeverity to emit.
void emit(
  Location loc,
  const Contradiction &contra,
  DiagnosticSeverity severity = DiagnosticSeverity::Error);

} // namespace mlir::Typing

#endif // MLIR_TYPING_CONTRADICTION_H
